// Generated by sd.config.mjs from tokens/motion.json. Do not edit.
export const duration = {
  "instant": 0.1,
  "fast": 0.15,
  "base": 0.24,
  "slow": 0.4,
  "slower": 0.6
} as const;

export const ease = {
  "out": [
    0.22,
    1,
    0.36,
    1
  ],
  "in": [
    0.4,
    0,
    1,
    1
  ],
  "inOut": [
    0.65,
    0,
    0.35,
    1
  ]
} as const;

export const stagger = {
  "base": 0.04
} as const;
