// Figma variables (exported as DTCG JSON into tokens/) → CSS custom properties + TS motion tokens.
// Run with `npm run tokens`. Output files are generated: edit tokens/*.json, never the output.
import StyleDictionary from "style-dictionary";

const isSemantic = (token) => token.filePath.includes("semantic");
const isMotion = (token) => token.path[0] === "motion";

// Motion tokens as typed TS, in the units Motion expects (seconds, bezier arrays).
StyleDictionary.registerFormat({
  name: "ts/motion",
  format: ({ dictionary }) => {
    const group = (name, toValue) =>
      Object.fromEntries(
        dictionary.allTokens
          .filter((t) => t.path[1] === name)
          .map((t) => [t.path[2].replace(/-(\w)/g, (_, c) => c.toUpperCase()), toValue(t.original.$value)]),
      );
    const seconds = (v) => parseFloat(v) / 1000;
    const out = {
      duration: group("duration", seconds),
      ease: group("ease", (v) => v),
      stagger: group("stagger", seconds),
    };
    return (
      "// Generated by sd.config.mjs from tokens/motion.json. Do not edit.\n" +
      Object.entries(out)
        .map(([k, v]) => `export const ${k} = ${JSON.stringify(v, null, 2)} as const;`)
        .join("\n\n") +
      "\n"
    );
  },
});

const light = new StyleDictionary({
  source: ["tokens/primitive.json", "tokens/semantic.light.json", "tokens/motion.json"],
  log: { verbosity: "silent" },
  platforms: {
    css: {
      transformGroup: "css",
      prefix: "ds",
      buildPath: "src/styles/",
      files: [
        {
          destination: "tokens.css",
          format: "css/variables",
          options: { outputReferences: true },
        },
      ],
    },
    ts: {
      transforms: ["name/kebab"],
      buildPath: "src/lib/motion/",
      files: [{ destination: "tokens.generated.ts", format: "ts/motion", filter: isMotion }],
    },
  },
});

// Dark mode: only the semantic layer changes; primitives stay in :root.
const dark = new StyleDictionary({
  source: ["tokens/primitive.json", "tokens/semantic.dark.json"],
  log: { verbosity: "silent" },
  platforms: {
    css: {
      transformGroup: "css",
      prefix: "ds",
      buildPath: "src/styles/",
      files: [
        {
          destination: "tokens.dark.css",
          format: "css/variables",
          filter: isSemantic,
          options: { selector: '[data-theme="dark"]', outputReferences: true },
        },
      ],
    },
  },
});

await light.buildAllPlatforms();
await dark.buildAllPlatforms();
console.log("tokens: built src/styles/tokens.css, tokens.dark.css, src/lib/motion/tokens.generated.ts");
